name: Deploy Next.js site to Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: vgd

      - name: Change directory
        run: |
          cd vgd

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "15"
          cache: npm

      - name: Install deps
        run: npm install

      - name: Build e Deploy
        run: |
          npm run build
          npm run deploy
